### ISSUE TITLE
Новый способ пробежки и присвоения значений в цикле для gprint.asm

### ISSUE THREAD

**Issue by DainVerd** [RazdolbayOne/assembly_labs_s3#4]
Также переделать сам способ индексикации масива

Так как BX регистр(значения )используеться для строк которые загоняют значение в видеопамять.

Плохо его использовать также как и индекс для масива значений из Vector ибо выходишь за границы масива

**Comment by ghost** [comment]
Fixed long agho

**Comment by DainVerd** [comment]
Fixed already
